# Generated by Django 3.1.5 on 2021-01-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witsuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='witsuser',
            name='send_messages',
            field=models.BooleanField(default=False),
        ),
    ]
