# Generated by Django 3.1.5 on 2021-01-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_opinion_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='level',
            field=models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], default='L', max_length=1),
        ),
    ]
